// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"benchmarks.mdx": () => import("../content/docs/benchmarks.mdx?collection=docs"), "comparison.mdx": () => import("../content/docs/comparison.mdx?collection=docs"), "faq.mdx": () => import("../content/docs/faq.mdx?collection=docs"), "api/chiapet.mdx": () => import("../content/docs/api/chiapet.mdx?collection=docs"), "api/hic.mdx": () => import("../content/docs/api/hic.mdx?collection=docs"), "api/hichip.mdx": () => import("../content/docs/api/hichip.mdx?collection=docs"), "api/index.mdx": () => import("../content/docs/api/index.mdx?collection=docs"), "api/utils.mdx": () => import("../content/docs/api/utils.mdx?collection=docs"), "cli/index.mdx": () => import("../content/docs/cli/index.mdx?collection=docs"), "getting-started/concepts.mdx": () => import("../content/docs/getting-started/concepts.mdx?collection=docs"), "getting-started/index.mdx": () => import("../content/docs/getting-started/index.mdx?collection=docs"), "getting-started/installation.mdx": () => import("../content/docs/getting-started/installation.mdx?collection=docs"), "getting-started/quickstart.mdx": () => import("../content/docs/getting-started/quickstart.mdx?collection=docs"), "guides/loop-calling.mdx": () => import("../content/docs/guides/loop-calling.mdx?collection=docs"), "guides/matrix-generation.mdx": () => import("../content/docs/guides/matrix-generation.mdx?collection=docs"), "guides/quality-control.mdx": () => import("../content/docs/guides/quality-control.mdx?collection=docs"), "guides/restriction-fragments.mdx": () => import("../content/docs/guides/restriction-fragments.mdx?collection=docs"), "tutorials/chiapet-tutorial.mdx": () => import("../content/docs/tutorials/chiapet-tutorial.mdx?collection=docs"), "tutorials/hic-tutorial.mdx": () => import("../content/docs/tutorials/hic-tutorial.mdx?collection=docs"), "tutorials/hichip-tutorial.mdx": () => import("../content/docs/tutorials/hichip-tutorial.mdx?collection=docs"), "tutorials/index.mdx": () => import("../content/docs/tutorials/index.mdx?collection=docs"), }),
};
export default browserCollections;